# Generated by Django 4.0.4 on 2022-06-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xboxliveaccount_microsoftaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBoxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gamertag', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user_id', models.TextField()),
                ('usertoken', models.TextField()),
                ('xsts_token', models.TextField()),
                ('xuid', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='xboxliveaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='MicrosoftAccount',
        ),
        migrations.DeleteModel(
            name='XboxLiveAccount',
        ),
    ]
