# Generated by Django 4.0.4 on 2022-06-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xboxaccount_remove_xboxliveaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xboxaccount',
            name='user_id',
        ),
    ]
