# Generated by Django 4.0.4 on 2022-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_xboxaccount_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxaccount',
            name='user_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
