# Generated by Django 4.0.4 on 2022-06-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_xboxaccount_xsts_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xboxaccount',
            name='xuid',
        ),
    ]
