# Generated by Django 4.0.4 on 2022-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_xboxaccount_xuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxaccount',
            name='mojang_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
