# Generated by Django 4.0.4 on 2022-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_xboxaccount_xbox_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxaccount',
            name='character',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xboxaccount',
            name='game_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
