# Generated by Django 4.0.4 on 2022-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_xboxaccount_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('data', models.JSONField(default={})),
            ],
        ),
    ]
