# Generated by Django 4.0.4 on 2022-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_rankings_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
